# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform M step of EM algorithm
#'
#' @param X design matrix
#' @export
M_step <- function(X, y_j, p, j, a, k, all_wts, keep, offset, theta, coefs_j, phi_j, cl_phi, est_covar, est_beta, lambda, alpha, IRLS_tol, CDA_tol, maxit_IRLS, maxit_CDA) {
    .Call(`_FSCseq_M_step`, X, y_j, p, j, a, k, all_wts, keep, offset, theta, coefs_j, phi_j, cl_phi, est_covar, est_beta, lambda, alpha, IRLS_tol, CDA_tol, maxit_IRLS, maxit_CDA)
}

